import { ChatOpenAI } from "@langchain/openai";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { config } from "dotenv";
import { z } from "zod";

config();

const testCasesSchema = z.object({
  test_cases: z
    .array(z.string().describe("test case"))
    .describe("Array of test cases"),
});

const promptTemplate = ChatPromptTemplate.fromMessages([
  [
    "system",
    `You are an expert DSA problem test case generator. You create test cases for a problem to test all the edge cases and time and space complexity of the solution with the help of test cases.

    You are given a problem statement, contraints and the input format example. You have to generate the test cases for the problem statement.

    Example:
    <example>
    Problem Statement:
    Given two strings s and t, return true if t is an anagram of s, and false otherwise.

    Constraints:
     - 1 <= s.length, t.length <= 5 * 10^4
     - s and t consist of lowercase English letters.

     Input Format:
     eg1: anagram\nnagaram
    eg2: rat\ncar


 <example>

 <expected_output>
    Expected Response Generated by you:
    ["anagram\\nnagaram","rat\\ncar"]
  <expected_output>
  <test_cases_requirements>
       - Test Cases generated must be valid according to the constraints and input format example provided.
       - Create total 20 test cases for the given problem statement.
       - 10 easy test cases and 5 medium and 5 hard test cases.
       - There should be at least 1 test case which will be testing the limit of constraints.
       - Returned array should be in JSON format.
    <test_cases_requirements>
    `.toString(),
  ],

  ["human", "{text}"],
]);

const llm = new ChatOpenAI({
  model: "gpt-4",
  temperature: 0,
  apiKey: process.env.OPENAI_API_KEY,
});

const structured_llm = llm.withStructuredOutput(testCasesSchema);

const problemStatement = `
        problem statement:
        Given two strings s and t, return true if t is an anagram of s, and false otherwise.

        constraints:
        - 1 <= s.length, t.length <= 5 * 10^4
        - s and t consist of lowercase English letters.

        input format:
         eg1: anagram\\nnagaram
         eg2: rat\\ncar`;

async function run() {
  const prompt = await promptTemplate.invoke({
    text: problemStatement,
  });
  const res = await structured_llm.invoke(prompt);

  console.log(res);
}

run();
